# NUM 9
print("Введите сумму вашего депозита")
d = float(input("Депозит: "))
p1 = float(d + (d*0.04))
p2 = float(p1 +(p1*0.04))
p3 = float(p2 + (p1*0.04))
p1 = ("{:.2f}".format(p1))
p2 = ("{:.2f}".format(p2))
p3 = ("{:.2f}".format(p3))
print("Ваша сумма после каждого года будет: \n")
print("Первый год: ", p1)
print("Второй год: ", p2)
print("Третий год: ", p3)
